// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UP_Korenkov_VM_285.Data;

#nullable disable

namespace UP_Korenkov_VM_285.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303132552_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("RequestId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasterId = 2,
                            Message = "Всё сделаем!",
                            RequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            MasterId = 3,
                            Message = "Всё сделаем!",
                            RequestId = 2
                        },
                        new
                        {
                            Id = 3,
                            MasterId = 3,
                            Message = "Починим в момент.",
                            RequestId = 3
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кондиционер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Увлажнитель воздуха"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сушилка для рук"
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MasterId")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepairParts")
                        .HasColumnType("text");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("MasterId");

                    b.HasIndex("RequestStatusId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 7,
                            EquipmentModel = "TCL TAC-12CHSA/TPG-W белый",
                            EquipmentTypeId = 1,
                            MasterId = 2,
                            ProblemDescription = "Не охлаждает воздух",
                            RequestStatusId = 1,
                            StartDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 8,
                            EquipmentModel = "Electrolux EACS/I-09HAT/N3_21Y белый",
                            EquipmentTypeId = 1,
                            MasterId = 3,
                            ProblemDescription = "Выключается сам по себе",
                            RequestStatusId = 1,
                            StartDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 9,
                            CompletionDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EquipmentModel = "Xiaomi Smart Humidifier 2",
                            EquipmentTypeId = 2,
                            MasterId = 3,
                            ProblemDescription = "Пар имеет неприятный запах",
                            RequestStatusId = 2,
                            StartDate = new DateTime(2022, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 8,
                            EquipmentModel = "Polaris PUH 2300 WIFI IQ Home",
                            EquipmentTypeId = 2,
                            ProblemDescription = "Увлажнитель воздуха продолжает работать при предельном снижении уровня воды",
                            RequestStatusId = 3,
                            StartDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 9,
                            EquipmentModel = "Ballu BAHD-1250",
                            EquipmentTypeId = 3,
                            ProblemDescription = "Не работает",
                            RequestStatusId = 3,
                            StartDate = new DateTime(2023, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В процессе ремонта"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Готова к выдаче"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Новая заявка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ожидание комплектующих"
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Менеджер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Специалист"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Оператор"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Заказчик"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Менеджер по качеству"
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Широков Василий Матвеевич",
                            Login = "login1",
                            PasswordHash = "$2a$11$XNX2Ay7t7mcrGLJLFKcIJezsXHXjemj575tM7gxNq/soVzCPXOjX6",
                            Phone = "89210563128",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Кудрявцева Ева Ивановна",
                            Login = "login2",
                            PasswordHash = "$2a$11$UuDO1cPKc8L4E8c/CJ/0N.Mc3PQaN/EL5z2A7UKlthN96pJm.4GPS",
                            Phone = "89535078985",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Гончарова Ульяна Ярославовна",
                            Login = "login3",
                            PasswordHash = "$2a$11$U.YPLPwmVzjGGd0XYZlPY.Sr61hdNqBPytmtxY2siZ4pwj9bzM.Du",
                            Phone = "89210673849",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Гусева Виктория Данииловна",
                            Login = "login4",
                            PasswordHash = "$2a$11$E0oaf2p3NcXUbrEVAyZbTO85TSSKOgUMwJgSbjJGcxSoaQqcQWbeC",
                            Phone = "89990563748",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Баранов Артём Юрьевич",
                            Login = "login5",
                            PasswordHash = "$2a$11$chDxwVuTRnv5Mvv0.rKwhOnEymsf2tZsAvQO9GkDPiR7szPVBRcxK",
                            Phone = "89994563847",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Овчинников Фёдор Никитич",
                            Login = "login6",
                            PasswordHash = "$2a$11$rBAsfgf3lifkuJ9ZtzQNSeUToCGv8lbwZVNDGkfAm6MdMGbedDhwu",
                            Phone = "89219567849",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Петров Никита Артёмович",
                            Login = "login7",
                            PasswordHash = "$2a$11$CrS7/dVfMeCv5/pyrKfA2eXuzediUzJcAoOR87/g.Z0i6oQ.Jd0AC",
                            Phone = "89219567841",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Ковалева Софья Владимировна",
                            Login = "login8",
                            PasswordHash = "$2a$11$xScEO6gZWTYEHGg8JrJpKuS3M8tczOso5KgHiw0R3uDY2Aufj3CKy",
                            Phone = "89219567842",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Кузнецов Сергей Матвеевич",
                            Login = "login9",
                            PasswordHash = "$2a$11$h5xiS6VB3EMuRP.fpfhyvuJWN12AjSq0iDp6w12DcmEuGUJLRNvFO",
                            Phone = "89219567843",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Беспалова Екатерина Даниэльевна",
                            Login = "login10",
                            PasswordHash = "$2a$11$6sePkQrsiY9uJR0gEGVUtu.ghMS98sfix96OMUS9bw0UH/hPcN8gK",
                            Phone = "89219567844",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Comment", b =>
                {
                    b.HasOne("UP_Korenkov_VM_285.Models.User", "Master")
                        .WithMany("Comments")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UP_Korenkov_VM_285.Models.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Request", b =>
                {
                    b.HasOne("UP_Korenkov_VM_285.Models.User", "Client")
                        .WithMany("ClientRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UP_Korenkov_VM_285.Models.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UP_Korenkov_VM_285.Models.User", "Master")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UP_Korenkov_VM_285.Models.RequestStatus", "RequestStatus")
                        .WithMany()
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("EquipmentType");

                    b.Navigation("Master");

                    b.Navigation("RequestStatus");
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.User", b =>
                {
                    b.HasOne("UP_Korenkov_VM_285.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.Request", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("UP_Korenkov_VM_285.Models.User", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("ClientRequests");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
